#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation
securinets_users:
    resource: "@SecurinetsUsersBundle/Resources/config/routing.yml"
    prefix:   /

securinets_front_office:
    resource: "@SecurinetsFrontOfficeBundle/Resources/config/routing.yml"
    prefix:   /

securinets_front_office_annotation:
    resource: "@SecurinetsFrontOfficeBundle/Controller/"
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
