getLogin:
    path: /getLogin
#    resource: "Securinets\UsersBundle\Controller\SecurityController"
#    pattern: /login
    defaults: { _controller: SecurinetsUsersBundle:Security:getLogin }

login:
    path: /login
    defaults: { _controller: SecurinetsUsersBundle:Security:login }

login_check:
    path: /login_check
#    pattern: /login_check

logout:
    path: /logout
#    pattern: /logout

getRegister:
    path: /getRegister
    defaults: { _controller: SecurinetsUsersBundle:Registration:getRegister }

register:
    path: /register
    defaults: { _controller: SecurinetsUsersBundle:Registration:register }


