parameters:
#    securinets_users.example.class: Securinets\UsersBundle\Example

services:
#    securinets_users.example:
#        class: %securinets_users.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
#servics:
#    request_injector:
#        class: RequestInjector
#        public: false
#        arguments: ['@service_container']
