index:
    path: /
#    resource: "Securinets\FrontOfficeBundle\Controller\DefaultController"
#    pattern : /
    defaults : { _controller: SecurinetsFrontOfficeBundle:Default:index}

home:
    path: /home
#    resource: "Securinets\FrontOfficeBundle\Controller\DefaultController"
#    pattern:  /home
    defaults: { _controller: SecurinetsFrontOfficeBundle:Default:home}

getRules:
    path: /getRules
#    resource: "Securinets\FrontOfficeBundle\Controller\DefaultController"
#    pattern: /getRules
    defaults: { _controller: SecurinetsFrontOfficeBundle:Default:getRules }

rules:
    path: /rules
    defaults: { _controller: SecurinetsFrontOfficeBundle:Default:rules }


getTasks:
    path: /getTasks
#    resource: "Securinets\FrontOfficeBundle\Controller\DefaultController"
#    pattern: /getTasks
    defaults: { _controller: SecurinetsFrontOfficeBundle:Challenge:getTasks }

tasks:
    path: /tasks
    defaults: { _controller: SecurinetsFrontOfficeBundle:Default:tasks }


validate:
    path: /validate/epreuve/{id}
#    resource: "Securinets\FrontOfficeBundle\Controller\DefaultController"
#    pattern : /validate/epreuve/{id}
    defaults: { _controller: SecurinetsFrontOfficeBundle:Challenge:validate , id : 0}
    requirements:
        id : \d+

getScore:
    path: /getScore
#    resource: "Securinets\FrontOfficeBundle\Controller\DefaultController"
#    pattern: /score
    defaults : { _controller: SecurinetsFrontOfficeBundle:Challenge:getScore }

score:
    path: /score
    defaults: { _controller: SecurinetsFrontOfficeBundle:Default:score }


erreurConnexion:
    path: /erreurConnexion
#    resource: "Securinets\FrontOfficeBundle\Controller\DefaultController"
#    pattern: /erreurConnexion
    defaults : { _controller: SecurinetsFrontOfficeBundle:Challenge:erreurConnexion }

getRemaingTime:
    path: /getRemaingTime
#    resource: "Securinets\FrontOfficeBundle\Controller\DefaultController"
#    pattern: /getRemaingTime
    defaults: { _controller: SecurinetsFrontOfficeBundle:Chrono:remaingTime}

getTask:
    path: /getTask/{id_epreuve}
#    resource: "Securinets\FrontOfficeBundle\Controller\DefaultController"
#    pattern : /getTask/{id_epreuve}
    defaults: { _controller: SecurinetsFrontOfficeBundle:Challenge:getTask,id_epreuve : 0}
    requirements:
        id : \d+

countDown:
    path: /countDown
#    resource: "Securinets\FrontOfficeBundle\Controller\DefaultController"
#    pattern : /countDown
    defaults: {  _controller: SecurinetsFrontOfficeBundle:Default:countDown } 

challengerInfo:
    path: /challengerInfo
#    resource: "Securinets\FrontOfficeBundle\Controller\DefaultController"
#    pattern : /challengerInfo
    defaults : {  _controller: SecurinetsFrontOfficeBundle:Challenge:challengerInfo }

getNews:
    path: /getNews
#    resource: "Securinets\FrontOfficeBundle\Controller\DefaultController"
#    pattern : /getNews
    defaults : { _controller : SecurinetsFrontOfficeBundle:Challenge:getNews }

getStat:
    path: /getStat
#    resource: "Securinets\FrontOfficeBundle\Controller\DefaultController"
#    pattern : /getStat
    defaults : { _controller : SecurinetsFrontOfficeBundle:Challenge:getStat }

stat:
    path: /stat
    defaults: { _controller: SecurinetsFrontOfficeBundle:Default:stat }


#getFlagForm:
#    path: /getFlagForm
#    resource: "Securinets\FrontOfficeBundle\Controller\DefaultController"
#    pattern : /getFlagForm
#    defaults : { _controller : SecurinetsFrontOfficeBundle:Challenge:getFlagForm }


#fos_user_resetting:
#    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
#    prefix: /resetting
