<?php

namespace Securinets\FrontOfficeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EpreuvesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EpreuveRepository extends EntityRepository
{
	
	public function getByListId($list)
	{
		$qb = $this->createQueryBuilder('e')
		           ->where('e.id2 in (:list)')
		           ->andWhere('e.isEnabled = true')
		           ->setParameter('list', $list);
		
		return $qb->getQuery()->getResult();
	}

	
}
